# Generated by Django 4.2.11 on 2024-04-02 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0002_categoria_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('escudo', models.CharField(max_length=500)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.categoria')),
                ('entrenadores', models.ManyToManyField(to='ClubBarrioApp.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyo', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='productos',
            name='cod_producto',
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.CreateModel(
            name='TutorLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPedido', models.IntegerField()),
                ('fecha', models.DateField(default='1900-01-01')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClubBarrioApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=500)),
                ('puntos_equipo1', models.IntegerField()),
                ('puntos_equipo2', models.IntegerField()),
                ('equipo1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_local', to='ClubBarrioApp.equipo')),
                ('equipo2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='equipo_visitante', to='ClubBarrioApp.equipo')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('articulo', models.TextField()),
                ('url_imagen', models.CharField(max_length=500)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.equipo')),
                ('tutorLegal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.tutorlegal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticasJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('minutos', models.IntegerField()),
                ('rebotes', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=250)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.entrenador')),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.usuario'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.usuario'),
        ),
        migrations.AddField(
            model_name='productos',
            name='pedidos',
            field=models.ManyToManyField(to='ClubBarrioApp.pedido'),
        ),
    ]
