# Generated by Django 5.0.3 on 2024-04-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0003_administrador_entrenador_equipo_temporada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(default='sin dirección', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='lugar',
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='sin dirección', max_length=500),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='lugarEntrenamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.lugarentrenamiento'),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField(default=0)),
                ('pedidos', models.ManyToManyField(to='ClubBarrioApp.pedido')),
                ('talla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.talla')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.tipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
