# Generated by Django 4.2.11 on 2024-04-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0004_lugarentrenamiento_talla_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('JUG', 'Jugador'), ('TUTOR', 'Tutor'), ('ENTRENADOR', 'Entrenador'), ('USUARIO', 'Usuario'), ('ADMIN', 'Administrador')], default='USUARIO', max_length=50)),
                ('fecha_nacimiento', models.DateField(default='1900-01-01')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='administrador',
            name='apellidos',
            field=models.CharField(default='sin apellidos', max_length=250),
        ),
        migrations.AddField(
            model_name='administrador',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=250),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='apellidos',
            field=models.CharField(default='sin apellidos', max_length=250),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=250),
        ),
        migrations.AddField(
            model_name='jugador',
            name='apellidos',
            field=models.CharField(default='sin apellidos', max_length=250),
        ),
        migrations.AddField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=250),
        ),
        migrations.AddField(
            model_name='tutorlegal',
            name='apellidos',
            field=models.CharField(default='sin apellidos', max_length=250),
        ),
        migrations.AddField(
            model_name='tutorlegal',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=250),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.user'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.user'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.user'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ClubBarrioApp.user'),
        ),
        migrations.AlterField(
            model_name='tutorlegal',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.user'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
