# Generated by Django 4.2.11 on 2024-04-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0005_user_administrador_apellidos_administrador_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('USUARIO', 'Usuario'), ('JUG', 'Jugador'), ('TUTOR', 'Tutor'), ('ENTRENADOR', 'Entrenador'), ('ADMIN', 'Administrador')], default='USUARIO', max_length=50),
        ),
    ]
