# Generated by Django 4.2.11 on 2024-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0006_alter_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutorlegal',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
