# Generated by Django 4.2.11 on 2024-04-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0007_jugador_es_activo_tutorlegal_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_imagen',
            field=models.CharField(default='sin imagen', max_length=500),
        ),
    ]
