# Generated by Django 4.2.11 on 2024-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0008_producto_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorlegal',
            name='tarifa',
            field=models.CharField(choices=[('BASE', 'Base'), ('PLUS', 'Plus'), ('PREMIUM', 'Premium')], default='BASE', max_length=50),
        ),
    ]
