# Generated by Django 4.2.11 on 2024-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0009_tutorlegal_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='puntos_equipo1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partido',
            name='puntos_equipo2',
            field=models.IntegerField(default=0),
        ),
    ]
