# Generated by Django 4.2.11 on 2024-04-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0011_partido_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='es_safa',
            field=models.BooleanField(default=False),
        ),
    ]
