# Generated by Django 4.2.11 on 2024-05-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0012_equipo_es_safa'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.equipo'),
        ),
    ]
