# Generated by Django 4.2.11 on 2024-05-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0015_notificaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificaciones',
            old_name='product_promotions',
            new_name='new_training',
        ),
    ]
