# Generated by Django 4.2.11 on 2024-05-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0016_rename_product_promotions_notificaciones_new_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foto',
            field=models.ImageField(default='foto_perfil/default.png', upload_to='foto_perfil'),
        ),
    ]
