# Generated by Django 4.2.11 on 2024-05-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0016_rename_product_promotions_notificaciones_new_training'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productotalla',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodoEnvio',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('CLUB', 'Club')], default='CLUB', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.pedido')),
                ('prductoTalla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.productotalla')),
            ],
        ),
    ]
