# Generated by Django 4.2.11 on 2024-05-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0017_remove_productotalla_pedidos_pedido_metodoenvio_and_more'),
        ('ClubBarrioApp', '0017_user_foto'),
    ]

    operations = [
    ]
