# Generated by Django 4.2.11 on 2024-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0018_merge_20240514_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
