# Generated by Django 4.2.11 on 2024-05-17 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0020_user_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.pedido'),
        ),
    ]
