# Generated by Django 4.2.11 on 2024-05-26 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0022_convocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='sin nombre', max_length=250)),
                ('apellidos', models.CharField(default='sin apellidos', max_length=250)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.equipo')),
            ],
        ),
    ]
