# Generated by Django 4.2.11 on 2024-05-26 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0023_presidente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='sin nombre', max_length=250)),
                ('apellidos', models.CharField(default='sin apellidos', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='arbitro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ClubBarrioApp.arbitro'),
        ),
    ]
