# Generated by Django 4.2.11 on 2024-05-28 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0026_valoraciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(default='sin motivo')),
                ('fecha', models.DateField(default='1900-01-01')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
