# Generated by Django 4.2.11 on 2024-05-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0027_reclamaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_oferta', models.FloatField()),
                ('fecha_fin', models.DateField(default='1900-01-01')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClubBarrioApp.producto')),
            ],
        ),
    ]
