# Generated by Django 4.2.11 on 2024-05-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClubBarrioApp', '0028_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotalla',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
